language: php

php:
  - 5.6.19
  - 7.0
  - 7.1

before_script:
  - pwd
  - cd ..
  - git clone https://github.com/mautic/mautic.git mautic
  - cd mautic
  - composer install
  - mv $TRAVIS_BUILD_DIR plugins
  - mv mautic-cronfig CronfigBundle
  - ls plugins

script:
  - bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter CronfigBundle
