language: php

php:
  - 5.6.19
  - 7.0
  - 7.1

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # install PHPSTAN for PHP 7+
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then composer global require phpstan/phpstan-shim; fi

before_script:
  - cd ..
  - git clone https://github.com/mautic/mautic.git mautic
  - cd mautic
  - composer install
  - mv $TRAVIS_BUILD_DIR plugins
  - mv plugins/mautic-cronfig plugins/CronfigBundle

script:
  - bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter CronfigBundle

  # Run PHPSTAN analysis for PHP 7+
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then ~/.composer/vendor/phpstan/phpstan-shim/phpstan.phar analyse Config Controller Model Tests
